name = "workflows-starter-template-wss"
main = "worker.js"
compatibility_date = "2026-03-13"
workers_dev = true

[[durable_objects.bindings]]
name = "HEAVY_DO"
class_name = "HeavyDo"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HeavyDo"]

[vars]
ENABLE_HEAVY_DO = "1"
HEAVY_DO_SHARDS = "4"

[observability]
enabled = true
